// flow-typed signature: 4e3028e529e3cd50cae7b99e8ac1df3c
// flow-typed version: <<STUB>>/react-native_v0.57.8/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native' {
  declare export var Platform: {
    OS: string,
  };
}
