// flow-typed signature: be5a1adf7265865b9bdaa55ae7b16d7d
// flow-typed version: <<STUB>>/ios-device-list_v1.1.32/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ios-device-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ios-device-list' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ios-device-list/build-devices' {
  declare module.exports: any;
}

declare module 'ios-device-list/dist/ios-device-list' {
  declare module.exports: any;
}

declare module 'ios-device-list/dist/ios-device-list.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ios-device-list/build-devices.js' {
  declare module.exports: $Exports<'ios-device-list/build-devices'>;
}
declare module 'ios-device-list/dist/ios-device-list.js' {
  declare module.exports: $Exports<'ios-device-list/dist/ios-device-list'>;
}
declare module 'ios-device-list/dist/ios-device-list.min.js' {
  declare module.exports: $Exports<'ios-device-list/dist/ios-device-list.min'>;
}
declare module 'ios-device-list/index' {
  declare module.exports: $Exports<'ios-device-list'>;
}
declare module 'ios-device-list/index.js' {
  declare module.exports: $Exports<'ios-device-list'>;
}
